## RPM sensor message topic
uint64 timestamp                      # time since system start (microseconds)
uint8 status 	# status of the sensor (0=OK, 1=fail)

uint64 rpm      # indicated rotor Frequency in Revolution per minute
uint8 current1 	# current from current sensor 1
uint8 current2	# current from current sensor 2

uint8 telem1_1 	# telem1 char values
uint8 telem1_2
uint8 telem1_3
uint8 telem1_4
uint8 telem1_5
uint8 telem1_6
uint8 telem1_7
uint8 telem1_8
uint8 telem1_9
uint8 telem1_10
uint8 telem1_11
uint8 telem1_12
uint8 telem1_13
uint8 telem1_14
uint8 telem1_15
uint8 telem1_16
uint8 telem1_17
uint8 telem1_18
uint8 telem1_19
uint8 telem1_20
uint8 telem1_21
uint8 telem1_22
uint8 telem1_23
uint8 telem1_24
uint8 telem1_25
uint8 telem1_26
uint8 telem1_27
uint8 telem1_28
uint8 telem1_29
uint8 telem1_30
uint8 telem1_31
uint8 telem1_32
uint8 telem1_33
uint8 telem1_34

uint8 telem2_1 	# telem2 char values
uint8 telem2_2
uint8 telem2_3
uint8 telem2_4
uint8 telem2_5
uint8 telem2_6
uint8 telem2_7
uint8 telem2_8
uint8 telem2_9
uint8 telem2_10
uint8 telem2_11
uint8 telem2_12
uint8 telem2_13
uint8 telem2_14
uint8 telem2_15
uint8 telem2_16
uint8 telem2_17
uint8 telem2_18
uint8 telem2_19
uint8 telem2_20
uint8 telem2_21
uint8 telem2_22
uint8 telem2_23
uint8 telem2_24
uint8 telem2_25
uint8 telem2_26
uint8 telem2_27
uint8 telem2_28
uint8 telem2_29
uint8 telem2_30
uint8 telem2_31
uint8 telem2_32
uint8 telem2_33
uint8 telem2_34

uint8 id

