#!/bin/sh
#
# @name my S500 quadcopter
#
# @type Quadrotor x
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
#
# @maintainer Juraj Mihalik <jm1e16@soton.ac.uk>
#

set VEHICLE_TYPE mc
param set MAV_TYPE 2

if [ $AUTOCNF = yes ]
then
	param set NAV_ACC_RAD 2

	param set RTL_RETURN_ALT 30
	param set RTL_DESCEND_ALT 10
	param set RTL_LAND_DELAY 0

	param set PWM_MAX 1950
	param set PWM_MIN 1230
	param set PWM_RATE 400

	param set SDLOG_PROFILE 27
fi

set MIXER my_LQR_S500_quad
set PWM_OUT 1234

my_LQR_control start -p 1

